### Ejercicios de NumPy

    1.Importa la librería de NumPy.

In [2]:
import numpy as np

    2.Crea un array de 1 dimension y 10 elementos.

In [41]:
arr1 = np.random.randint(0,100,(10))
arr1

array([10, 93, 29, 81,  3, 63, 20, 78, 30, 11])

    3.Reemplaza todos los números impares por el valor "impar" y los pares por "par". Para hacer esto os tendréis que crear un array nuevo donde vayáis añadiendo los valores nuevos.

In [47]:
#Creamos un array vacio con la misma forma que el array anterior
#Especificamos que los elementos del array sean dtype = '<U8' 
# para que acepten hasta 8 caracteres

arr_par_impar = np.empty_like(arr1, dtype ='<U8')


#Creamos un rango del mismo tamaño que la longitud del array
# y lo usamos para iterar por los indices del array original
#Introducimos el resultado en el array vacío

for i in range(arr1.shape[0]):
    if arr1[i]%2 != 0:
        arr_par_impar[i] = 'impar'
    else:
        arr_par_impar[i] = 'par'        
        
arr_par_impar        

array(['par', 'impar', 'impar', 'impar', 'impar', 'impar', 'par', 'par',
       'par', 'impar'], dtype='<U8')

    4.Cambiad la forma del array del ejercicio 3 a un array de 2 filas y 5 columnas.

In [43]:
arr2 = arr_par_impar.reshape((2,5))
arr2

array([['par', 'impar', 'impar', 'impar', 'impar'],
       ['impar', 'par', 'par', 'par', 'impar']], dtype='<U8')

    5.Extrae los elementos comunes de los siguientes arrays

array1 = np.array([1,2,3,2,3,4,3,4,5,6])

array2 = np.array([7,2,10,2,7,4,9,4,9,8])

In [45]:
array1 = np.array([1,2,3,2,3,4,3,4,5,6])
array2 = np.array([7,2,10,2,7,4,9,4,9,8])

In [56]:
comunes = np.intersect1d(array1, array2)
print(f'Los elementos comunes de los dos arrays son {comunes}')

Los elementos comunes de los dos arrays son [2 4]


    6.Extraed los elementos que están en el array1 pero no en el array2.

In [58]:
solamente = np.setdiff1d(array1, array2)
print(f'Los elementos que estan en array1 y que no estan en array2 son {solamente}')

Los elementos que estan en array1 y que no estan en array2 son [1 3 5 6]


    7.Extraed las posiciones donde tengamos elementos que sean iguales.

In [60]:
posiciones = np.where(array1 == array2)
print(f'Las posiciones en las que hay elementos iguales en ambos arrays son {posiciones[0]}')

Las posiciones en las que hay elementos iguales en ambos arrays son [1 3 5 7]


    8.Cread un array de 3 filas y 5 columnas, con números enteros del 0 al 50. Una vez creado, extrae los valores que sean menores que 10 y mayores que 40.

In [61]:
array3 = np.random.randint(0,50,(3,5))
array3

array([[ 3, 42,  4, 35, 49],
       [13, 39,  0, 17, 35],
       [ 1, 24,  6, 34,  5]])

In [73]:
valores = []
for y in range(array3.shape[0]):
    for x in range(array3.shape[1]):
        if array3[y,x] <10 or array3[y,x] >40:
           valores.append(array3[y,x])
        else: 
            pass
        
print(f'Los valores del array que son menores que 10 o mayores que 40 son {valores}')     

Los valores del array que son menores que 10 o mayores que 40 son [3, 42, 4, 49, 0, 1, 6, 5]


    9.Cread un array de 5x3 con números decimales aleatorios entre el 5 y el 10.

In [71]:
array4 = np.random.uniform(5,10,(5,3))
array4

array([[8.80928373, 5.03238771, 9.50889731],
       [6.77134781, 6.4063632 , 7.2132793 ],
       [6.83701229, 8.58355632, 9.87659031],
       [9.19718797, 8.9159894 , 6.48595779],
       [7.65833276, 9.09676689, 5.05274348]])

    10.Crea un array de tres dimensiones de 2x4x7 con números entre el 1 y el 20

        -Transponed el array para que tenga 4 matrices, 7 filas y 2 columnas

In [72]:
array5 = np.random.randint(1,20,(2,4,7))
array5

array([[[18, 19, 18,  7, 17, 17, 15],
        [ 4,  6,  8, 16, 14,  7, 17],
        [13,  8,  3, 17,  2, 10,  6],
        [11,  6,  8, 19, 11, 18, 18]],

       [[ 5,  9, 19,  2,  2, 10, 13],
        [15, 16,  3, 18,  4, 18, 19],
        [ 2,  2,  6,  7,  5,  3,  3],
        [10,  4, 17,  4,  6, 19, 10]]])

In [74]:
array6 = array5.reshape((4,7,2))
array6

array([[[18, 19],
        [18,  7],
        [17, 17],
        [15,  4],
        [ 6,  8],
        [16, 14],
        [ 7, 17]],

       [[13,  8],
        [ 3, 17],
        [ 2, 10],
        [ 6, 11],
        [ 6,  8],
        [19, 11],
        [18, 18]],

       [[ 5,  9],
        [19,  2],
        [ 2, 10],
        [13, 15],
        [16,  3],
        [18,  4],
        [18, 19]],

       [[ 2,  2],
        [ 6,  7],
        [ 5,  3],
        [ 3, 10],
        [ 4, 17],
        [ 4,  6],
        [19, 10]]])